import type { BookDetail, Collection } from "../types";

export const demoCollections: Collection[] = [
  { id: 1, name: "Science Fiction", description: "Worlds beyond our own", bookCount: 5, covers: [] },
  { id: 2, name: "Favorites", description: "The keepers", bookCount: 3, covers: [] },
  { id: 3, name: "Read in 2026", description: "This year's journey", bookCount: 4, covers: [] },
  { id: 4, name: "Reference", description: "Books worth returning to", bookCount: 2, covers: [] }
];

const cover = (name: string) => `/covers/${name}.svg`;
export const demoBooks: BookDetail[] = [
  { id: 1, title: "Dune", subtitle: "Book One of the Dune Chronicles", authors: ["Frank Herbert"], description: "A sweeping story of politics, ecology, power, and survival on the desert planet Arrakis.", publicationYear: 1965, format: "Paperback", status: "Reading", rating: 5, coverUrl: cover("dune"), tags: ["science fiction", "favorite"], collectionIds: [1,2], dateAdded: "2026-01-04", currentPage: 284, pageCount: 688, isbn13: "9780441172719", publisher: "Ace", language: "English", location: "Living Room · Shelf A", condition: "Very Good", notes: "The ecology is even richer on a reread.", series: "Dune", seriesPosition: 1, dateStarted: "2026-08-20" },
  { id: 2, title: "The Left Hand of Darkness", authors: ["Ursula K. Le Guin"], description: "An envoy arrives on a world without fixed gender and learns the cost of understanding another culture.", publicationYear: 1969, format: "Paperback", status: "Finished", rating: 5, coverUrl: cover("left-hand"), tags: ["science fiction", "favorite"], collectionIds: [1,2,3], dateAdded: "2026-01-19", pageCount: 304, publisher: "Ace", language: "English", location: "Study · Shelf B", notes: "Quiet, wintry, humane.", dateFinished: "2026-02-12" },
  { id: 3, title: "The Hobbit", authors: ["J. R. R. Tolkien"], description: "Bilbo Baggins leaves his comfortable home for an unexpected journey.", publicationYear: 1937, format: "Hardcover", status: "Finished", rating: 5, coverUrl: cover("hobbit"), tags: ["fantasy", "favorite"], collectionIds: [2,3], dateAdded: "2025-12-11", pageCount: 310, publisher: "Houghton Mifflin", language: "English", location: "Living Room · Shelf A", dateFinished: "2026-01-21" },
  { id: 4, title: "1984", authors: ["George Orwell"], description: "A chilling portrait of a totalitarian society and the struggle to remain human.", publicationYear: 1949, format: "Mass Market Paperback", status: "Finished", rating: 4, coverUrl: cover("1984"), tags: ["classic"], collectionIds: [3], dateAdded: "2026-03-02", pageCount: 328, publisher: "Signet", language: "English", location: "Bedroom · Bookcase", dateFinished: "2026-04-16" },
  { id: 5, title: "Neuromancer", authors: ["William Gibson"], description: "A washed-up computer hacker is hired for one last impossible job.", publicationYear: 1984, format: "Paperback", status: "Want to Read", coverUrl: cover("neuromancer"), tags: ["cyberpunk", "science fiction"], collectionIds: [1], dateAdded: "2026-04-08", pageCount: 271, publisher: "Ace", language: "English", location: "Study · Shelf B" },
  { id: 6, title: "The Martian", authors: ["Andy Weir"], description: "An astronaut stranded on Mars engineers his way toward survival.", publicationYear: 2014, format: "Ebook", status: "Finished", rating: 4, coverUrl: cover("martian"), tags: ["science fiction"], collectionIds: [1,3], dateAdded: "2026-05-03", pageCount: 369, publisher: "Crown", language: "English", dateFinished: "2026-06-07" },
  { id: 7, title: "Frankenstein", subtitle: "The Modern Prometheus", authors: ["Mary Shelley"], description: "A scientist creates life and recoils from what he has made.", publicationYear: 1818, format: "Hardcover", status: "Unread", coverUrl: cover("frankenstein"), tags: ["classic", "gothic"], collectionIds: [], dateAdded: "2026-06-22", pageCount: 280, publisher: "Penguin Classics", language: "English", location: "Bedroom · Bookcase" },
  { id: 8, title: "Foundation", authors: ["Isaac Asimov"], description: "A mathematician predicts the fall of a galactic empire and builds a sanctuary for knowledge.", publicationYear: 1951, format: "Paperback", status: "Want to Read", coverUrl: cover("foundation"), tags: ["science fiction"], collectionIds: [1], dateAdded: "2026-07-14", pageCount: 255, publisher: "Bantam", language: "English", location: "Living Room · Shelf A", series: "Foundation", seriesPosition: 1 },
  { id: 9, title: "The Dispossessed", authors: ["Ursula K. Le Guin"], description: "A physicist crosses between twin worlds divided by ideology.", publicationYear: 1974, format: "Paperback", status: "Reading", rating: 4, coverUrl: cover("dispossessed"), tags: ["science fiction"], collectionIds: [1], dateAdded: "2026-08-01", currentPage: 112, pageCount: 387, publisher: "Harper", language: "English", location: "Nightstand", dateStarted: "2026-09-01" },
  { id: 10, title: "A Brief History of Time", authors: ["Stephen Hawking"], description: "A lucid journey through cosmology, time, and the shape of the universe.", publicationYear: 1988, format: "Hardcover", status: "Did Not Finish", rating: 3, coverUrl: cover("brief-history"), tags: ["science", "reference"], collectionIds: [4], dateAdded: "2026-08-12", currentPage: 76, pageCount: 256, publisher: "Bantam", language: "English", location: "Study · Shelf B" }
];
