import { BookCopy, Edit3, Plus, Trash2, X } from "lucide-react";
import { useState } from "react";
import type { BookDetail, Collection } from "../types";

export function CollectionsPage({collections,books,onCreate,onRename,onDelete,onOpenBook}:{collections:Collection[];books:BookDetail[];onCreate:(n:string,d:string)=>Promise<void>;onRename:(id:number,n:string,d:string)=>Promise<void>;onDelete:(id:number)=>Promise<void>;onOpenBook:(b:BookDetail)=>void}){
  const [selected,setSelected]=useState<number|null>(null);const [creating,setCreating]=useState(false);const [renaming,setRenaming]=useState(false);const [name,setName]=useState("");const [description,setDescription]=useState("");
  const current=collections.find(c=>c.id===selected);const currentBooks=current?books.filter(b=>b.collectionIds.includes(current.id)):[];
  const create=async(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return;await onCreate(name.trim(),description.trim());setName("");setDescription("");setCreating(false)};
  const rename=async(e:React.FormEvent)=>{e.preventDefault();if(!current||!name.trim())return;await onRename(current.id,name.trim(),description.trim());setRenaming(false)};
  return <div className="page collections-page">
    <section className="section-heading"><div><h2>Curated shelves</h2><p>Group books by mood, subject, or whatever matters to you.</p></div><button className="button primary" onClick={()=>setCreating(true)}><Plus size={16}/>New collection</button></section>
    <div className="collection-grid">{collections.map((c,i)=>{const cb=books.filter(b=>b.collectionIds.includes(c.id));return <article className="collection-card" key={c.id} onClick={()=>setSelected(c.id)} tabIndex={0}><div className={`collection-collage tone-${i%4}`}>{cb.slice(0,3).map((b,j)=><div key={b.id} style={{transform:`translateX(${j*46}px) rotate(${(j-1)*-4}deg)`,zIndex:j}}>{b.coverUrl&&<img src={b.coverUrl} alt=""/>}</div>)}{!cb.length&&<BookCopy size={42}/>}</div><div><h3>{c.name}</h3><p>{c.description||"A personal shelf"}</p><span>{cb.length} {cb.length===1?"book":"books"}</span></div></article>})}</div>
    {!collections.length&&<section className="empty-state"><BookCopy size={42}/><h2>No collections yet</h2><p>Create a shelf for favorites, a subject, or this year’s reading.</p></section>}
    {creating&&<div className="modal-backdrop"><form className="small-modal" onSubmit={create}><header><div><span className="form-kicker">New shelf</span><h2>Create collection</h2></div><button type="button" className="icon-button" onClick={()=>setCreating(false)}><X size={19}/></button></header><label>Name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Favorites" required/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="The keepers"/></label><footer className="form-actions"><button type="button" className="button secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="button primary">Create collection</button></footer></form></div>}
    {current&&<div className="drawer-layer" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><aside className="collection-drawer"><header className="drawer-header"><span>Collection</span><button className="icon-button" onClick={()=>setSelected(null)}><X size={19}/></button></header><div className="collection-drawer-copy"><span className="form-kicker">{currentBooks.length} books</span><h2>{current.name}</h2><p>{current.description}</p></div><div className="collection-book-list">{currentBooks.map(b=><button key={b.id} onClick={()=>onOpenBook(b)}>{b.coverUrl?<img src={b.coverUrl} alt=""/>:<i/>}<span><strong>{b.title}</strong><small>{b.authors.join(", ")}</small></span></button>)}{!currentBooks.length&&<p className="muted">This collection is empty. Add books from the book editor.</p>}</div><footer className="drawer-actions"><button className="button danger-quiet" onClick={async()=>{await onDelete(current.id);setSelected(null)}}><Trash2 size={16}/>Delete collection</button><button className="button secondary" onClick={()=>{setName(current.name);setDescription(current.description||"");setRenaming(true)}}><Edit3 size={16}/>Rename</button></footer></aside></div>}
    {renaming&&current&&<div className="modal-backdrop"><form className="small-modal" onSubmit={rename}><header><div><span className="form-kicker">Collection</span><h2>Rename collection</h2></div><button type="button" className="icon-button" onClick={()=>setRenaming(false)}><X size={19}/></button></header><label>Name<input autoFocus value={name} onChange={e=>setName(e.target.value)} required/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3}/></label><footer className="form-actions"><button type="button" className="button secondary" onClick={()=>setRenaming(false)}>Cancel</button><button className="button primary">Save changes</button></footer></form></div>}
  </div>;
}
