import { Check, Database, Download, FolderOpen, Info, Moon, RotateCcw, Sun, Upload } from "lucide-react";
import type { AppInfo } from "../types";

export function SettingsPage({dark,onTheme,info,onExport,onReset}:{dark:boolean;onTheme:(d:boolean)=>void;info:AppInfo|null;onExport:()=>Promise<void>;onReset:()=>void}){
  return <div className="page settings-page"><section className="settings-column">
    <article className="settings-card"><header><span><Sun size={18}/></span><div><h3>Appearance</h3><p>Choose how Meridian looks on this device.</p></div></header><div className="setting-row"><div><strong>Theme</strong><small>A quieter light palette or a deep reading-room dark mode.</small></div><div className="theme-choice"><button className={!dark?"active":""} onClick={()=>onTheme(false)}><Sun size={16}/>Light{!dark&&<Check size={14}/>}</button><button className={dark?"active":""} onClick={()=>onTheme(true)}><Moon size={16}/>Dark{dark&&<Check size={14}/>}</button></div></div></article>
    <article className="settings-card"><header><span><Database size={18}/></span><div><h3>Library data</h3><p>Your catalog stays on this computer.</p></div></header><div className="path-card"><FolderOpen size={17}/><div><small>Database</small><code>{info?.databasePath||"Loading…"}</code></div></div><div className="path-card"><FolderOpen size={17}/><div><small>Cover storage</small><code>{info?.coversPath||"Loading…"}</code></div></div></article>
    <article className="settings-card"><header><span><Download size={18}/></span><div><h3>Backup & restore</h3><p>Keep a portable copy of your catalog and reading history.</p></div></header><div className="setting-row"><div><strong>Export library</strong><small>Saves books, authors, tags, collections, and reading data as JSON.</small></div><button className="button secondary" onClick={onExport}><Download size={16}/>Export backup</button></div><div className="setting-row disabled"><div><strong>Import backup</strong><small>Restore from a Meridian backup file.</small></div><button className="button secondary" disabled><Upload size={16}/>Choose file</button></div></article>
    <article className="settings-card"><header><span><Info size={18}/></span><div><h3>About Meridian</h3><p>A private home for the books that shape you.</p></div></header><div className="setting-row"><div><strong>Application version</strong><small>Meridian Desktop</small></div><code>{info?.version||"0.1.0"}</code></div>{!('__TAURI_INTERNALS__' in window)&&<div className="setting-row"><div><strong>Reset preview data</strong><small>Restore the sample library in this browser preview.</small></div><button className="button danger-quiet" onClick={onReset}><RotateCcw size={16}/>Reset</button></div>}</article>
  </section></div>;
}
