use rusqlite::{params, params_from_iter, Connection, OptionalExtension, Transaction};
use rusqlite::types::Value;
use crate::{domain::{BookDetail,BookInput,BookQuery,Collection,CountItem,Statistics},error::{AppError,AppResult}};

pub struct LibraryRepository;
fn clean(v:&Option<String>)->Option<String>{v.as_ref().map(|s|s.trim().to_string()).filter(|s|!s.is_empty())}
impl LibraryRepository {
  pub fn create(conn:&mut Connection,input:&BookInput)->AppResult<BookDetail>{
    if input.title.trim().is_empty(){return Err(AppError::MissingTitle)} let tx=conn.transaction()?;let id=Self::insert_graph(&tx,input)?;tx.commit()?;Self::get(conn,id)
  }
  pub(crate) fn insert_graph(tx:&Transaction,input:&BookInput)->AppResult<i64>{
    tx.execute("INSERT INTO works(title,subtitle,description,original_publication_year,series,series_position) VALUES(?1,?2,?3,?4,?5,?6)",params![input.title.trim(),clean(&input.subtitle),clean(&input.description),input.publication_year,clean(&input.series),input.series_position])?;
    let work=tx.last_insert_rowid();
    for (pos,name) in input.authors.iter().map(|x|x.trim()).filter(|x|!x.is_empty()).enumerate(){tx.execute("INSERT INTO authors(name) VALUES(?1) ON CONFLICT(name) DO NOTHING",[name])?;let aid:i64=tx.query_row("SELECT id FROM authors WHERE name=?1 COLLATE NOCASE",[name],|r|r.get(0))?;tx.execute("INSERT INTO work_authors(work_id,author_id,position) VALUES(?1,?2,?3)",params![work,aid,pos as i64])?;}
    tx.execute("INSERT INTO editions(work_id,isbn10,isbn13,publisher,publication_year,page_count,language,format,cover_url) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9)",params![work,clean(&input.isbn10),clean(&input.isbn13),clean(&input.publisher),input.publication_year,input.page_count,clean(&input.language),input.format,clean(&input.cover_url)])?;
    let edition=tx.last_insert_rowid();tx.execute("INSERT INTO library_copies(edition_id,physical_location,date_acquired,condition,notes) VALUES(?1,?2,?3,?4,?5)",params![edition,clean(&input.location),clean(&input.date_acquired),clean(&input.condition),clean(&input.notes)])?;let copy=tx.last_insert_rowid();
    tx.execute("INSERT INTO reading_records(copy_id,status,current_page,date_started,date_finished,rating,review) VALUES(?1,?2,?3,?4,?5,?6,?7)",params![copy,input.status,input.current_page,clean(&input.date_started),clean(&input.date_finished),input.rating,clean(&input.review)])?;
    Self::replace_tags(tx,copy,&input.tags)?;Self::replace_collections(tx,copy,&input.collection_ids)?;Ok(copy)
  }
  fn replace_tags(tx:&Transaction,copy:i64,tags:&[String])->AppResult<()>{tx.execute("DELETE FROM copy_tags WHERE copy_id=?1",[copy])?;for name in tags.iter().map(|x|x.trim()).filter(|x|!x.is_empty()){tx.execute("INSERT INTO tags(name) VALUES(?1) ON CONFLICT(name) DO NOTHING",[name])?;let id:i64=tx.query_row("SELECT id FROM tags WHERE name=?1 COLLATE NOCASE",[name],|r|r.get(0))?;tx.execute("INSERT OR IGNORE INTO copy_tags(copy_id,tag_id) VALUES(?1,?2)",params![copy,id])?;}Ok(())}
  fn replace_collections(tx:&Transaction,copy:i64,ids:&[i64])->AppResult<()>{tx.execute("DELETE FROM collection_copies WHERE copy_id=?1",[copy])?;for id in ids{tx.execute("INSERT OR IGNORE INTO collection_copies(collection_id,copy_id) VALUES(?1,?2)",params![id,copy])?;}Ok(())}
  pub fn update(conn:&mut Connection,id:i64,input:&BookInput)->AppResult<BookDetail>{
    if input.title.trim().is_empty(){return Err(AppError::MissingTitle)} let tx=conn.transaction()?;
    let ids:Option<(i64,i64)>=tx.query_row("SELECT e.work_id,c.edition_id FROM library_copies c JOIN editions e ON e.id=c.edition_id WHERE c.id=?1",[id],|r|Ok((r.get(0)?,r.get(1)?))).optional()?;let (work,edition)=ids.ok_or(AppError::NotFound)?;
    tx.execute("UPDATE works SET title=?1,subtitle=?2,description=?3,original_publication_year=?4,series=?5,series_position=?6,updated_at=CURRENT_TIMESTAMP WHERE id=?7",params![input.title.trim(),clean(&input.subtitle),clean(&input.description),input.publication_year,clean(&input.series),input.series_position,work])?;
    tx.execute("DELETE FROM work_authors WHERE work_id=?1",[work])?;for (pos,name) in input.authors.iter().map(|x|x.trim()).filter(|x|!x.is_empty()).enumerate(){tx.execute("INSERT INTO authors(name) VALUES(?1) ON CONFLICT(name) DO NOTHING",[name])?;let aid:i64=tx.query_row("SELECT id FROM authors WHERE name=?1 COLLATE NOCASE",[name],|r|r.get(0))?;tx.execute("INSERT INTO work_authors(work_id,author_id,position) VALUES(?1,?2,?3)",params![work,aid,pos as i64])?;}
    tx.execute("UPDATE editions SET isbn10=?1,isbn13=?2,publisher=?3,publication_year=?4,page_count=?5,language=?6,format=?7,cover_url=?8 WHERE id=?9",params![clean(&input.isbn10),clean(&input.isbn13),clean(&input.publisher),input.publication_year,input.page_count,clean(&input.language),input.format,clean(&input.cover_url),edition])?;
    tx.execute("UPDATE library_copies SET physical_location=?1,date_acquired=?2,condition=?3,notes=?4 WHERE id=?5",params![clean(&input.location),clean(&input.date_acquired),clean(&input.condition),clean(&input.notes),id])?;
    let rr:Option<i64>=tx.query_row("SELECT id FROM reading_records WHERE copy_id=?1 ORDER BY id DESC LIMIT 1",[id],|r|r.get(0)).optional()?;if let Some(rid)=rr{tx.execute("UPDATE reading_records SET status=?1,current_page=?2,date_started=?3,date_finished=?4,rating=?5,review=?6 WHERE id=?7",params![input.status,input.current_page,clean(&input.date_started),clean(&input.date_finished),input.rating,clean(&input.review),rid])?;}else{tx.execute("INSERT INTO reading_records(copy_id,status,current_page,date_started,date_finished,rating,review) VALUES(?1,?2,?3,?4,?5,?6,?7)",params![id,input.status,input.current_page,clean(&input.date_started),clean(&input.date_finished),input.rating,clean(&input.review)])?;}
    Self::replace_tags(&tx,id,&input.tags)?;Self::replace_collections(&tx,id,&input.collection_ids)?;tx.commit()?;Self::get(conn,id)
  }
  pub fn delete(conn:&Connection,id:i64)->AppResult<()>{if conn.execute("DELETE FROM library_copies WHERE id=?1",[id])?==0{return Err(AppError::NotFound)}Ok(())}
  pub fn get(conn:&Connection,id:i64)->AppResult<BookDetail>{
    let mut b:BookDetail=conn.query_row("SELECT c.id,w.title,w.subtitle,w.description,w.original_publication_year,w.series,w.series_position,e.isbn10,e.isbn13,e.publisher,e.page_count,e.language,e.format,e.cover_url,c.physical_location,c.condition,c.notes,c.date_acquired,c.date_added,COALESCE(r.status,'Unread'),r.current_page,r.rating,r.review,r.date_started,r.date_finished FROM library_copies c JOIN editions e ON e.id=c.edition_id JOIN works w ON w.id=e.work_id LEFT JOIN reading_records r ON r.id=(SELECT id FROM reading_records WHERE copy_id=c.id ORDER BY id DESC LIMIT 1) WHERE c.id=?1",[id],|r|Ok(BookDetail{id:r.get(0)?,title:r.get(1)?,subtitle:r.get(2)?,authors:vec![],description:r.get(3)?,publication_year:r.get(4)?,series:r.get(5)?,series_position:r.get(6)?,isbn10:r.get(7)?,isbn13:r.get(8)?,publisher:r.get(9)?,page_count:r.get(10)?,language:r.get(11)?,format:r.get(12)?,cover_url:r.get(13)?,location:r.get(14)?,condition:r.get(15)?,notes:r.get(16)?,date_acquired:r.get(17)?,date_added:r.get(18)?,status:r.get(19)?,current_page:r.get(20)?,rating:r.get(21)?,review:r.get(22)?,date_started:r.get(23)?,date_finished:r.get(24)?,tags:vec![],collection_ids:vec![]})).optional()?.ok_or(AppError::NotFound)?;
    b.authors=Self::strings(conn,"SELECT a.name FROM authors a JOIN work_authors wa ON wa.author_id=a.id JOIN editions e ON e.work_id=wa.work_id JOIN library_copies c ON c.edition_id=e.id WHERE c.id=?1 ORDER BY wa.position",id)?;
    b.tags=Self::strings(conn,"SELECT t.name FROM tags t JOIN copy_tags ct ON ct.tag_id=t.id WHERE ct.copy_id=?1 ORDER BY t.name",id)?;
    let mut st=conn.prepare("SELECT collection_id FROM collection_copies WHERE copy_id=?1")?;b.collection_ids=st.query_map([id],|r|r.get(0))?.collect::<Result<Vec<i64>,_>>()?;Ok(b)
  }
  fn strings(conn:&Connection,sql:&str,id:i64)->AppResult<Vec<String>>{let mut st=conn.prepare(sql)?;let rows=st.query_map([id],|r|r.get(0))?.collect::<Result<Vec<String>,_>>()?;Ok(rows)}
  pub fn list(conn:&Connection,q:&BookQuery)->AppResult<Vec<BookDetail>>{
    let mut sql=String::from("SELECT DISTINCT c.id FROM library_copies c JOIN editions e ON e.id=c.edition_id JOIN works w ON w.id=e.work_id LEFT JOIN reading_records r ON r.id=(SELECT id FROM reading_records WHERE copy_id=c.id ORDER BY id DESC LIMIT 1) LEFT JOIN work_authors wa ON wa.work_id=w.id LEFT JOIN authors a ON a.id=wa.author_id LEFT JOIN copy_tags ct ON ct.copy_id=c.id LEFT JOIN tags t ON t.id=ct.tag_id LEFT JOIN collection_copies cc ON cc.copy_id=c.id WHERE 1=1");let mut values:Vec<Value>=vec![];
    if let Some(s)=q.search.as_ref().map(|s|s.trim()).filter(|s|!s.is_empty()){sql.push_str(" AND (w.title LIKE ? OR w.subtitle LIKE ? OR a.name LIKE ? OR e.isbn10 LIKE ? OR e.isbn13 LIKE ? OR w.series LIKE ? OR t.name LIKE ?)");let p=Value::Text(format!("%{s}%"));for _ in 0..7{values.push(p.clone())}}
    if let Some(s)=q.status.as_ref().filter(|s|*s!="All"){sql.push_str(" AND r.status=?");values.push(Value::Text(s.clone()))}if let Some(s)=q.format.as_ref().filter(|s|*s!="All"){sql.push_str(" AND e.format=?");values.push(Value::Text(s.clone()))}if let Some(n)=q.min_rating{sql.push_str(" AND r.rating>=?");values.push(Value::Integer(n as i64))}if let Some(id)=q.collection_id{sql.push_str(" AND cc.collection_id=?");values.push(Value::Integer(id))}
    sql.push_str(match q.sort.as_deref(){Some("title_asc")=>" ORDER BY w.title COLLATE NOCASE",Some("author_asc")=>" ORDER BY a.name COLLATE NOCASE",Some("publication_year_desc")=>" ORDER BY w.original_publication_year DESC",Some("rating_desc")=>" ORDER BY r.rating DESC",_=>" ORDER BY c.date_added DESC,c.id DESC"});
    let mut st=conn.prepare(&sql)?;let ids=st.query_map(params_from_iter(values),|r|r.get(0))?.collect::<Result<Vec<i64>,_>>()?;ids.into_iter().map(|id|Self::get(conn,id)).collect()
  }
  pub fn collections(conn:&Connection)->AppResult<Vec<Collection>>{let mut st=conn.prepare("SELECT c.id,c.name,c.description,count(cc.copy_id) FROM collections c LEFT JOIN collection_copies cc ON cc.collection_id=c.id GROUP BY c.id ORDER BY c.name")?;let rows=st.query_map([],|r|Ok(Collection{id:r.get(0)?,name:r.get(1)?,description:r.get(2)?,book_count:r.get(3)?,covers:vec![]}))?.collect::<Result<Vec<_>,_>>()?;Ok(rows)}
  pub fn create_collection(conn:&Connection,name:&str,description:&str)->AppResult<Collection>{conn.execute("INSERT INTO collections(name,description) VALUES(?1,NULLIF(?2,''))",params![name.trim(),description.trim()])?;Ok(Collection{id:conn.last_insert_rowid(),name:name.trim().into(),description:if description.trim().is_empty(){None}else{Some(description.trim().into())},book_count:0,covers:vec![]})}
  pub fn rename_collection(conn:&Connection,id:i64,name:&str,description:&str)->AppResult<Collection>{if conn.execute("UPDATE collections SET name=?1,description=NULLIF(?2,'') WHERE id=?3",params![name.trim(),description.trim(),id])?==0{return Err(AppError::NotFound)}let all=Self::collections(conn)?;all.into_iter().find(|c|c.id==id).ok_or(AppError::NotFound)}
  pub fn delete_collection(conn:&Connection,id:i64)->AppResult<()>{if conn.execute("DELETE FROM collections WHERE id=?1",[id])?==0{return Err(AppError::NotFound)}Ok(())}
  pub fn statistics(conn:&Connection)->AppResult<Statistics>{
    let scalar=|sql:&str|conn.query_row(sql,[],|r|r.get::<_,i64>(0));let total=scalar("SELECT count(*) FROM library_copies")?;let finished=scalar("SELECT count(*) FROM reading_records WHERE status='Finished'")?;let reading=scalar("SELECT count(*) FROM reading_records WHERE status='Reading'")?;let unread=scalar("SELECT count(*) FROM reading_records WHERE status='Unread'")?;let added=scalar("SELECT count(*) FROM library_copies WHERE strftime('%Y',date_added)=strftime('%Y','now')")?;let fy=scalar("SELECT count(*) FROM reading_records WHERE status='Finished' AND strftime('%Y',date_finished)=strftime('%Y','now')")?;let pages=scalar("SELECT COALESCE(sum(e.page_count),0) FROM reading_records r JOIN library_copies c ON c.id=r.copy_id JOIN editions e ON e.id=c.edition_id WHERE r.status='Finished'")?;let avg=conn.query_row("SELECT avg(rating) FROM reading_records WHERE rating IS NOT NULL",[],|r|r.get(0))?;
    fn counts(conn:&Connection,sql:&str)->AppResult<Vec<CountItem>>{let mut st=conn.prepare(sql)?;let rows=st.query_map([],|r|Ok(CountItem{label:r.get(0)?,value:r.get(1)?}))?.collect::<Result<Vec<_>,_>>()?;Ok(rows)}
    let top=counts(conn,"SELECT a.name,count(DISTINCT c.id) FROM authors a JOIN work_authors wa ON wa.author_id=a.id JOIN editions e ON e.work_id=wa.work_id JOIN library_copies c ON c.edition_id=e.id GROUP BY a.id ORDER BY 2 DESC LIMIT 5")?;let status=counts(conn,"SELECT status,count(*) FROM reading_records GROUP BY status ORDER BY count(*) DESC")?;let formats=counts(conn,"SELECT format,count(*) FROM editions GROUP BY format ORDER BY count(*) DESC")?;let mut activity=vec![];for month in 1..=12{let value:i64=conn.query_row("SELECT count(*) FROM reading_records WHERE status='Finished' AND strftime('%Y',date_finished)=strftime('%Y','now') AND CAST(strftime('%m',date_finished) AS INTEGER)=?1",[month],|r|r.get(0))?;activity.push(CountItem{label:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][(month-1)as usize].into(),value})}Ok(Statistics{total_books:total,finished,reading,unread,added_this_year:added,finished_this_year:fy,pages_read:pages,average_rating:avg,top_authors:top,status_counts:status,format_counts:formats,activity})
  }
}
